[package]
name = "dune"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dune"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.46.0"
threadpool = "1.8.1"
anyhow = "1.0.52"
colored = "2.0.0"
path-clean = "0.1.0"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
lazy_static = "1.4.0"
sha = "1.0.3"
nanoid = "0.4.0"
regex = "1.5.5"
dirs = "4.0.0"
path-absolutize = "3.0.12"
ureq = { version = "2.4.0", features = ["charset"] }
phf = { version = "0.10.1", features = ["macros"] }
url = "2.2.2"
clearscreen = "1.0.10"
serde = { version = "1.0.136", features = ["derive"] }
rmp-serde = "1.0.0"

[dev-dependencies]
assert_fs = "1.0.7"
